<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputTypeEx>CSharp.WinExe</OutputTypeEx>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\hw.UnitTest\hw.UnitTest.dev.csproj" />
        <Using Include="hw.DebugFormatter" />
        <Using Include="hw.Helper" />
        <Using Include="hw.UnitTest" />
    </ItemGroup>
</Project>