<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetTypeEx>CSharp.Library</TargetTypeEx>
        <PackageReadmeFile>docs\$(AssemblyName).md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\hw.Helper.Core\hw.Helper.Core.dev.csproj" />
    </ItemGroup>
</Project>